"""empty message

Revision ID: 2a3f6c59609f
Revises: 8fe294b68b4e
Create Date: 2025-12-16 15:07:40.157210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3f6c59609f'
down_revision = '8fe294b68b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
